Repository showMeTheMoneyPrac/FE_repo, pull requests merged in 2022-05, with the labels that each got.

#3 유저 페이지 기본 레이아웃 구현 및 테스트 코드 작성
  package-lock.json
  package.json
  src/App.js
  src/components/user/PurchaseList.jsx
  src/components/user/SideBar.jsx
  src/components/user/UserInfo.jsx
  src/components/user/UserTemplate.jsx
  src/components/user/__tests__/SideBar.test.jsx
  src/pages/UserPage.jsx
Labels: feat, style, test

#5 유저 페이지 사이드 바 테스트 코드 수정
  src/components/user/__tests__/SideBar.test.jsx
Labels: test

#8 공통 헤더 기본 레이아웃 구현 및 테스트 코드 작성
  src/App.js
  src/components/common/Header.jsx
  src/components/common/SearchBar.jsx
  src/components/common/__test__/Header.test.jsx
  src/components/common/__test__/SearchBar.test.jsx
  src/pages/MainPage.jsx
Labels: feat, style, test

#11 사이드 바 네비게이션 테스트 코드 작성
  package-lock.json
  package.json
  src/App.js
  src/components/user/__tests__/SideBar.test.jsx
Labels: test

#12 유저 페이지 공통 템플릿 및 사이드 바 UI 구현
  src/components/user/SideBar.jsx
  src/components/user/UserTemplate.jsx
Labels: style

#15 내 정보 컴포넌트 테스트 코드 작성
  src/components/user/SideBar.jsx
  src/components/user/__tests__/UserInfo.test.jsx
  src/pages/UserPage.jsx
Labels: test

#16 내 정보 컴포넌트 기본 UI 구현
  src/components/user/UserInfo.jsx
Labels: style

#24 로그인 회원가입 모달 구현
  package-lock.json
  package.json
  src/App.js
  src/components/common/Header.jsx
  src/components/common/SearchBar.jsx
  src/components/form/LabelInput.jsx
  src/components/form/LoginForm.jsx
  src/components/form/RegistForm.jsx
  src/components/modal/LoginModal.jsx
  src/components/modal/MemberModal.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ModalOverlay.jsx
  src/components/modal/RegistModal.jsx
  src/index.js
  src/redux/configStore.js
  src/redux/modules/modal.js
Labels: feat, style

#27 회원가입 구현
  public/index.html
  src/api/user.js
  src/components/form/LabelInput.jsx
  src/components/form/LoginForm.jsx
  src/components/form/RegistForm.jsx
  src/redux/configStore.js
  src/redux/modules/form.js
Labels: feat

#30 내 정보 변경 구현
  src/api/user.js
  src/components/user/PurchaseItem.jsx
  src/components/user/UserInfo.jsx
  src/components/user/UserTemplate.jsx
  src/hooks/useInput.js
  src/hooks/useToggle.js
Labels: feat, style

#32 회원 탈퇴 구현
  src/api/user.js
  src/components/user/UserInfo.jsx
  src/pages/UserPage.jsx
Labels: feat, style

#36 메인페이지 UI 구현
  src/App.js
  src/components/common/Header.jsx
  src/components/modal/ModalOverlay.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductTemplate.jsx
  src/pages/MainPage.jsx
  src/redux/modules/form.js
Labels: style

#37 구매 목록 요청 기능 구현 및 UI 변경
  package-lock.json
  package.json
  src/api/product.js
  src/components/user/PurchaseDetail.jsx
  src/components/user/PurchaseItem.jsx
  src/components/user/PurchaseList.jsx
  src/components/user/UserInfo.jsx
Labels: feat, style

#38 회원 탈퇴 확인 UI 구현
  src/components/user/PurchaseDetail.jsx
  src/components/user/StyledCheckbox.jsx
  src/components/user/UserInfo.jsx
  src/components/user/WithdrawalForm.jsx
  src/hooks/useSelect.js
  src/hooks/useToggle.js
Labels: feat, style

#40 상품 리스트 UI 구현
  src/components/common/SearchBar.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortList.jsx
  src/components/product/ProductSortNav.jsx
  src/components/product/ProductTemplate.jsx
Labels: style

#41 리뮤 모달 구현
  src/components/modal/ReviewModal.jsx
  src/components/user/PurchaseDetail.jsx
  src/components/user/PurchaseList.jsx
  src/components/user/UserInfo.jsx
  src/redux/modules/modal.js
Labels: feat, style

#42 상품 리스트 UI 및 라우팅 처리 구현
  src/components/common/Header.jsx
  src/components/common/SearchBar.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortList.jsx
  src/components/product/ProductSortNav.jsx
  src/components/product/ProductTemplate.jsx
  src/components/product/ScrollBtn.jsx
  src/hooks/useSearchQuery.js
Labels: feat, style

#44 상품 리스트 UI 수정 및 상품리스트 API 구현
  src/api/product.js
  src/components/common/Header.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortNav.jsx
  src/components/product/ProductTemplate.jsx
  src/components/product/ScrollBtn.jsx
Labels: feat, style

#46 리덕스 코드 분리
  package-lock.json
  package.json
  src/api/product.js
  src/api/purchse.js
  src/api/review.js
  src/components/user/PurchaseDetail.jsx
  src/components/user/PurchaseList.jsx
  src/components/user/PurchaseReview.jsx
  src/redux/configStore.js
  src/redux/modules/modal.js
  src/redux/modules/purchase.js
  src/redux/sagas/index.js
  src/redux/sagas/purchaseSaga.js
Labels: refactor, feat

#49 리뷰 기능 구현
  src/api/purchase.js
  src/api/purchse.js
  src/api/review.js
  src/components/modal/ReviewModal.jsx
  src/components/user/PurchaseList.jsx
  src/components/user/PurchaseReview.jsx
  src/components/user/UserInfo.jsx
  src/hooks/useInput.js
  src/redux/configStore.js
  src/redux/modules/purchase.js
  src/redux/sagas/index.js
  src/redux/sagas/purchaseSaga.js
Labels: feat

#51 장바구니 UI 구현
  src/App.js
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketList.jsx
  src/components/bucket/BucketResult.jsx
  src/components/bucket/BucketTemplate.jsx
  src/components/common/Spacer.jsx
  src/components/common/StyledCheckbox.jsx
  src/components/user/PurchaseDetail.jsx
  src/components/user/SideBar.jsx
  src/components/user/UserTemplate.jsx
  src/components/user/WithdrawalForm.jsx
  src/pages/BucketPage.jsx
Labels: style

#53 장바구니 불러오기 및 삭제 기능 구현
  src/api/bucket.js
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketList.jsx
  src/redux/configStore.js
  src/redux/modules/bucket.js
  src/redux/sagas/bucketSaga.js
  src/redux/sagas/index.js
Labels: feat

#56 상품상세페이지 레이아웃 구현 및 장바구니 담기 구현
  src/App.js
  src/api/cart.js
  src/api/product.js
  src/components/product/ProductDetail.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortNav.jsx
  src/components/product/ProductTemplate.jsx
  src/components/product/ScrollBtn.jsx
  src/pages/ProductDetailPage.jsx
  src/redux/configStore.js
  src/redux/modules/product.js
  src/redux/sagas/index.js
  src/redux/sagas/productSaga.js
Labels: feat, style

#58 대체 이미지 컴포넌트 구현
  src/components/bucket/BucketItem.jsx
  src/components/common/NoImage.jsx
  src/redux/sagas/index.js
Labels: style

#59 장바구니 상품 수량 변경 결제 미리보기 구현
  src/api/bucket.js
  src/api/user.js
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketList.jsx
  src/components/bucket/BucketResult.jsx
  src/components/user/UserInfo.jsx
  src/redux/modules/bucket.js
  src/redux/modules/user.js
  src/redux/sagas/index.js
  src/redux/sagas/userSaga.js
Labels: feat, style

#61 장바구니 결제 기능 구현
  src/api/bucket.js
  src/components/bucket/BucketItem.jsx
  src/components/bucket/BucketResult.jsx
Labels: feat

#62 게시물 리스트 UI 수정
  src/api/product.js
  src/components/product/Lodaing.jsx
  src/components/product/ProductDetail.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductTemplate.jsx
  src/redux/modules/product.js
  src/redux/sagas/productSaga.js
Labels: feat, style

#65 장바구니 상품 수량 변경 구현
  src/api/bucket.js
  src/components/bucket/BucketItem.jsx
  src/redux/modules/bucket.js
  src/redux/sagas/bucketSaga.js
Labels: feat

#67 상품 환불 기능 구현
  src/api/purchase.js
  src/components/user/PurchaseDetail.jsx
  src/components/user/PurchaseList.jsx
  src/redux/modules/purchase.js
  src/redux/sagas/purchaseSaga.js
Labels: feat

#68 게시물 리스트 UI 수정
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortList.jsx
  src/components/product/ProductSortNav.jsx
  src/components/product/ProductTemplate.jsx
  src/components/product/ScrollBtn.jsx
Labels: style

#70 게시물 리스트 UI 수정
  src/api/cart.js
  src/api/purchase.js
  src/components/common/Header.jsx
  src/components/product/ProductDetail.jsx
  src/components/product/ProductItem.jsx
  src/components/product/ProductList.jsx
  src/components/product/ReviewList.jsx
Labels: feat, style

#71 게시물 라우팅 처리 수정 및 게시물 상세페이지 UI 수정
  src/components/product/ProductDetail.jsx
  src/components/product/ProductList.jsx
  src/components/product/ProductNav.jsx
  src/components/product/ProductSortList.jsx
Labels: refactor, style

#74 게시물 상세 페이지 UI 수정
  src/components/product/ProductDetail.jsx
Labels: style
